name: Update Console SVG

on:
  schedule:
    - cron: "0 0 * * *" # once a day at midnight UTC
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build console.svg
        run: |
          # -------------------------------
          # CONFIG
          # -------------------------------
          WIDTH=1200
          HEIGHT=2600
          FONT="14px/24px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
          TITLE="Aryan Gupta ‚Äî Console README"
          DESCRIPTION="Console style read me profile"

          COLOR_BG="#0d1117"
          COLOR_BAR="#161b22"
          COLOR_CLOSE="#ff5f57"
          COLOR_MIN="#febc2e"
          COLOR_MAX="#28c840"
          COLOR_PROMPT="#3fb950"
          COLOR_CMD="#79c0ff"
          COLOR_TEXT="#c9d1d9"
          COLOR_DIM="#8b949e"
          COLOR_ACCENT="#e3b341"
          COLOR_LINK="#58a6ff"
          COLOR_WARN="#f85149"
          COLOR_SUCCESS="#3fb950"

          # -------------------------------
          # CONSOLE CONTENT
          # -------------------------------
          CONSOLE_CONTENT='
              <!-- whoami -->
              <text x="24" y="80"><tspan class="prompt">$ </tspan><tspan class="cmd">whoami</tspan></text>
              <text x="24" y="104" class="text"><tspan class="accent">Aryan Gupta</tspan> ‚Äî CS @ Northeastern University | John Martinson ºs Honors Program | 4.0 GPA</text>
              <text x="24" y="128" class="dim">üìç Boston, MA | Available for Co-ops/Internships: Jan ‚Äì Sep 2026</text>

              <!-- about-me -->
              <text x="24" y="180"><tspan class="prompt">$ </tspan><tspan class="cmd">about-me --verbose</tspan></text>
              <text x="24" y="204" class="dim">&gt; Passionate about blending technology with creativity to address real-world challenges.</text>
              <text x="24" y="228" class="dim">&gt; Full-stack engineer with experience from fast-paced startups to cutting-edge research labs.</text>
              <text x="24" y="252" class="dim">&gt; Leading teams while staying deeply involved in code ‚Äî from architecture to implementation.</text>
              <text x="24" y="276" class="dim">&gt; Co-director @ Oasis Project Series ‚Äî teaching web dev to 100+ students.</text>

              <!-- current-roles -->
              <text x="24" y="328"><tspan class="prompt">$ </tspan><tspan class="cmd">cat current-roles.txt</tspan></text>
              <text x="24" y="356" class="success">‚úì Teaching Assistant ‚Äî Discrete Structures @ Northeastern</text>
              <text x="40" y="380" class="text">Teaching 500+ students | Weekly recitations for 20+ students each</text>
              <text x="40" y="404" class="text">Graph theory, proofs, combinatorics, logic | Office hours | Grading assignments</text>
              
              <text x="24" y="432" class="success">‚úì Quak Travel ‚Äî Software Engineer</text>
              <text x="40" y="456" class="text">Leading engineering team building AI-powered travel platform</text>
              
              <text x="24" y="484" class="success">‚úì Barbershop Operations and Client Management ‚Äî Software Engineer Intern</text>
              <text x="40" y="508" class="text">Independently developed iOS app streamlining booking, payments, and scheduling</text>
              <text x="40" y="532" class="text">10+ barber clients | Improved retention by 20% | Loading times 60% faster with Zustand</text>
              <text x="40" y="556" class="text">Assisted in UI/UX redesign across all platforms</text>
              
              <text x="24" y="584" class="success">‚úì Optical Neural Networks Research ‚Äî Undergrad Researcher</text>
              <text x="40" y="608" class="text">Working with Dr. Yongmin Liu on cutting-edge ONN research</text>
              <text x="40" y="632" class="text">Developing GNN architectures for meta-surface electric field predictions</text>
              <text x="40" y="656" class="text">80% accuracy achieved | 50% reduction in training time and data requirements</text>
              <text x="40" y="680" class="text">Hands-on with photonics, meta-materials, ML frameworks</text>
              
              <text x="24" y="708" class="success">‚úì Northeastern Electric Racing ‚Äî Tech Lead</text>
              <text x="40" y="732" class="text">Leading 10+ developer team on FinishLine management suite for 50+ engineers</text>
              <text x="40" y="756" class="text">Implementing Rules Compliance Dashboard - upload, assign, track competition rules</text>
              <text x="40" y="780" class="text">Drive technical strategy, architecture decisions, mentoring team members</text>
              <text x="40" y="804" class="text">Sprint planning, code reviews, technical roadmap in agile environment</text>
              
              <text x="24" y="832" class="success">‚úì Oasis @ Northeastern ‚Äî Project Series Co-Director</text>
              <text x="40" y="856" class="text">Co-directing program teaching web dev to 100+ students</text>
              <text x="40" y="880" class="text">Led curriculum design, mentoring, and workshops</text>
              <text x="40" y="904" class="text">Previously led CoDesign team - 5 devs, showcased to 100+ people</text>
              
              <text x="24" y="932" class="success">‚úì Knack ‚Äî Computer Science Tutor</text>
              <text x="40" y="956" class="text">Tutoring: CS1, CS2, Discrete Structures, Math Reasoning, Cybersecurity</text>
              <text x="40" y="980" class="text">Helping students master fundamentals through personalized sessions</text>

              <!-- experience timeline -->
              <text x="24" y="1032"><tspan class="prompt">$ </tspan><tspan class="cmd">git log --oneline --work</tspan></text>
              <text x="40" y="1060"><tspan class="accent">aug2025</tspan><tspan class="text">  Started TA position for Discrete Structures ‚Äî 500+ students</tspan></text>
              <text x="40" y="1084"><tspan class="accent">jun2025</tspan><tspan class="text">  Joined Barbershop Operations and Client Management</tspan></text>
              <text x="40" y="1108"><tspan class="accent">may2025</tspan><tspan class="text">  Promoted to Tech Lead @ NER | Co-Director @ Oasis</tspan></text>
              <text x="40" y="1132"><tspan class="accent">mar2025</tspan><tspan class="text">  Started tutoring CS courses on Knack platform</tspan></text>
              <text x="40" y="1156"><tspan class="accent">feb2025</tspan><tspan class="text">  Joined Quak Travel ‚Äî Built platform, secured funding</tspan
