name: Update Console SVG

on:
  schedule:
    - cron: "0 0 * * *" # once a day at midnight UTC
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build console.svg
        run: |
          # -------------------------------
          # CONFIG
          # -------------------------------
          WIDTH=1200
          HEIGHT=2480
          FONT="14px/24px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
          TITLE="Aryan Gupta ‚Äî Console README"
          DESCRIPTION="Console style read me profile"

          COLOR_BG="#0d1117"
          COLOR_BAR="#161b22"
          COLOR_CLOSE="#ff5f57"
          COLOR_MIN="#febc2e"
          COLOR_MAX="#28c840"
          COLOR_PROMPT="#3fb950"
          COLOR_CMD="#79c0ff"
          COLOR_TEXT="#c9d1d9"
          COLOR_DIM="#8b949e"
          COLOR_ACCENT="#e3b341"
          COLOR_LINK="#58a6ff"
          COLOR_WARN="#f85149"
          COLOR_SUCCESS="#3fb950"

          # -------------------------------
          # CONSOLE CONTENT
          # -------------------------------
          CONSOLE_CONTENT='
              <!-- whoami -->
              <text x="24" y="80"><tspan class="prompt">$ </tspan><tspan class="cmd">whoami</tspan></text>
              <text x="24" y="104" class="text"><tspan class="accent">Aryan Gupta</tspan> ‚Äî CS @ Northeastern University | John Martinson ºs Honors Program | 4.0 GPA</text>
              <text x="24" y="128" class="dim">üìç Boston, MA | Available for Co-ops/Internships: Jan ‚Äì Sep 2026</text>

              <!-- about-me -->
              <text x="24" y="176"><tspan class="prompt">$ </tspan><tspan class="cmd">about-me --verbose</tspan></text>
              <text x="24" y="200" class="dim">&gt; Passionate about blending technology with creativity to address real-world challenges.</text>
              <text x="24" y="224" class="dim">&gt; Full-stack engineer with experience from fast-paced startups to cutting-edge research labs.</text>
              <text x="24" y="248" class="dim">&gt; Leading teams while staying deeply involved in code ‚Äî from architecture to implementation.</text>

              <!-- current-role -->
              <text x="24" y="296"><tspan class="prompt">$ </tspan><tspan class="cmd">cat current-roles.txt</tspan></text>
              <text x="24" y="320" class="success">‚úì Teaching Assistant ‚Äî Discrete Structures @ Northeastern</text>
              <text x="24" y="344" class="text">  Teaching 500+ students | Weekly recitations for 20+ students each</text>
              <text x="24" y="368" class="text">  Graph theory, proofs, combinatorics, logic | Office hours | Grading assignments</text>
              
              <text x="24" y="392" class="success">‚úì Quak Travel ‚Äî Software Engineer</text>
              <text x="24" y="416" class="text">  Leading engineering team building AI-powered travel platform</text>
              
              <text x="24" y="440" class="success">‚úì Barbershop Operations and Client Management ‚Äî Software Engineer Intern</text>
              <text x="24" y="464" class="text">  Independently developed iOS app streamlining booking, payments, and scheduling</text>
              <text x="24" y="488" class="text">  10+ barber clients | Improved retention by 20% | Loading times 60% faster with Zustand</text>
              <text x="24" y="512" class="text">  Assisted in UI/UX redesign across all platforms</text>
              
              <text x="24" y="536" class="success">‚úì Optical Neural Networks Research ‚Äî Undergrad Researcher</text>
              <text x="24" y="560" class="text">  Working with Dr. Yongmin Liu on cutting-edge ONN research</text>
              <text x="24" y="584" class="text">  Developing GNN architectures for meta-surface electric field predictions</text>
              <text x="24" y="608" class="text">  80% accuracy achieved | 50% reduction in training time and data requirements</text>
              <text x="24" y="632" class="text">  Hands-on with photonics, meta-materials, ML frameworks</text>
              
              <text x="24" y="656" class="success">‚úì Northeastern Electric Racing ‚Äî Tech Lead</text>
              <text x="24" y="680" class="text">  Leading 10+ developer team on FinishLine management suite for 50+ engineers</text>
              <text x="24" y="704" class="text">  Implementing Rules Compliance Dashboard - upload, assign, track competition rules</text>
              <text x="24" y="728" class="text">  Drive technical strategy, architecture decisions, mentoring team members</text>
              <text x="24" y="752" class="text">  Sprint planning, code reviews, technical roadmap in agile environment</text>
              
              <text x="24" y="776" class="success">‚úì Oasis @ Northeastern ‚Äî Project Series Co-Director</text>
              <text x="24" y="800" class="text">  Co-directing program teaching web dev to 100+ students</text>
              <text x="24" y="824" class="text">  Led curriculum design, mentoring, and workshops</text>
              <text x="24" y="848" class="text">  Previously led CoDesign team - 5 devs, showcased to 100+ people</text>
              
              <text x="24" y="872" class="success">‚úì Knack ‚Äî Computer Science Tutor</text>
              <text x="24" y="896" class="text">  Tutoring: CS1, CS2, Discrete Structures, Math Reasoning, Cybersecurity</text>
              <text x="24" y="920" class="text">  Helping students master fundamentals through personalized sessions</text>

              <!-- experience timeline -->
              <text x="24" y="968"><tspan class="prompt">$ </tspan><tspan class="cmd">git log --oneline --work</tspan></text>
              <text x="24" y="992"><tspan class="accent">aug2025</tspan> Started TA position for Discrete Structures ‚Äî 500+ students</text>
              <text x="24" y="1016"><tspan class="accent">jun2025</tspan> Joined Barbershop Operations and Client Management</text>
              <text x="24" y="1040"><tspan class="accent">may2025</tspan> Promoted to Tech Lead @ NER | Co-Director @ Oasis</text>
              <text x="24" y="1064"><tspan class="accent">mar2025</tspan> Started tutoring CS courses on Knack platform</text>
              <text x="24" y="1088"><tspan class="accent">feb2025</tspan> Joined Quak Travel ‚Äî Built platform, secured funding</text>
              <text x="24" y="1112"><tspan class="accent">jan2025</tspan> Led CoDesign team @ Oasis ‚Äî 5 devs, 100+ demo viewers</text>
              <text x="24" y="1136"><tspan class="accent">oct2024</tspan> Started Research @ Nano-Optics Lab</text>
              <text x="24" y="1160"><tspan class="accent">sep2024</tspan> Joined NER as Web Developer ‚Äî FinishLine platform</text>

              <!-- projects -->
              <text x="24" y="1208"><tspan class="prompt">$ </tspan><tspan class="cmd">ls -la ~/projects/</tspan></text>
              <text x="24" y="1232" class="accent">drwxr-xr-x  rainfall-learning/</text>
              <text x="24" y="1256" class="text">  ‚îî‚îÄ Live tutoring platform solving lack of collaborative coding in online education</text>
              <text x="24" y="1280" class="text">     Leading 20+ member team</text>
              <text x="24" y="1304" class="text">     Core UI: Embedded IDE with CRDT-based real-time collaboration</text>
              <text x="24" y="1328" class="text">     Video meetings, curriculum viewer, interactive Python lessons</text>
              <text x="24" y="1352" class="text">     Tech: React, TypeScript, Express, PostgreSQL, ViTest, Docusaurus</text>
              <text x="24" y="1376" class="text">     CI/CD: GitHub Actions, Docker containerization, automated testing</text>
              
              <text x="24" y="1400" class="accent">drwxr-xr-x  codesign/</text>
              <text x="24" y="1424" class="text">  ‚îî‚îÄ Social platform connecting developers/designers for startup collaborations</text>
              <text x="24" y="1448" class="text">     Led 5-person team | 2-month sprint | Showcased to 100+ at Oasis demo day</text>
              <text x="24" y="1472" class="text">     Features: User profiles, Google OAuth, real-time messaging</text>
              <text x="24" y="1496" class="text">     Smart matchmaking algorithms based on skills/interests</text>
              <text x="24" y="1520" class="text">     Secure JWT auth, Bcrypt encryption, scalable REST APIs</text>
              <text x="24" y="1544" class="text">     Tech: React, React Native, Flask, MongoDB | Web + Mobile clients</text>

              <!-- tech stack - ORGANIZED AND SORTED -->
              <text x="24" y="1592"><tspan class="prompt">$ </tspan><tspan class="cmd">tech-stack --categorized</tspan></text>
              <text x="24" y="1616" class="success">Languages:</text>
              <text x="24" y="1640" class="dim">  Python ‚Ä¢ Java ‚Ä¢ JavaScript ‚Ä¢ TypeScript ‚Ä¢ Swift ‚Ä¢ SQL ‚Ä¢ HTML ‚Ä¢ CSS ‚Ä¢ Go ‚Ä¢ GraphQL ‚Ä¢ LaTeX ‚Ä¢ Markdown</text>
              <text x="24" y="1664" class="success">Frontend:</text>
              <text x="24" y="1688" class="dim">  React ‚Ä¢ React Native ‚Ä¢ React Query ‚Ä¢ React Router ‚Ä¢ React Hook Form ‚Ä¢ TailwindCSS ‚Ä¢ MUI ‚Ä¢ Expo</text>
              <text x="24" y="1712" class="success">Backend:</text>
              <text x="24" y="1736" class="dim">  Node.js ‚Ä¢ Express.js ‚Ä¢ Flask ‚Ä¢ Django ‚Ä¢ Socket.io ‚Ä¢ JWT ‚Ä¢ Prisma ‚Ä¢ Nodemon</text>
              <text x="24" y="1760" class="success">Databases:</text>
              <text x="24" y="1784" class="dim">  PostgreSQL ‚Ä¢ MongoDB ‚Ä¢ Firebase ‚Ä¢ Supabase</text>
              <text x="24" y="1808" class="success">Cloud/DevOps:</text>
              <text x="24" y="1832" class="dim">  AWS ‚Ä¢ Docker ‚Ä¢ GitHub Actions ‚Ä¢ Vercel ‚Ä¢ Netlify ‚Ä¢ Render</text>
              <text x="24" y="1856" class="success">ML/Data:</text>
              <text x="24" y="1880" class="dim">  TensorFlow ‚Ä¢ PyTorch ‚Ä¢ OpenCV ‚Ä¢ NumPy ‚Ä¢ Pandas ‚Ä¢ Matplotlib ‚Ä¢ Scikit-learn</text>
              <text x="24" y="1904" class="success">Tools:</text>
              <text x="24" y="1928" class="dim">  Git ‚Ä¢ GitHub ‚Ä¢ Postman ‚Ä¢ Swagger ‚Ä¢ OpenAPI ‚Ä¢ Figma ‚Ä¢ Prettier ‚Ä¢ NPM ‚Ä¢ Yarn ‚Ä¢ Vite ‚Ä¢ Twilio ‚Ä¢ Raspberry Pi</text>

              <!-- currently-learning -->
              <text x="24" y="1976"><tspan class="prompt">$ </tspan><tspan class="cmd">tail -f learning.log</tspan></text>
              <text x="24" y="2000" class="dim">[2025-09-15] Learning Rust for systems programming</text>
              <text x="24" y="2024" class="dim">[2025-09-14] Studying distributed systems architecture</text>
              <text x="24" y="2048" class="dim">[2025-09-13] Preparing for AWS Cloud Practitioner certification</text>
              <text x="24" y="2072" class="dim">[2025-09-12] Diving into systems level programming</text>
              <text x="24" y="2096" class="dim">[2025-09-11] Exploring LLMs and AI fundamentals</text>

              <!-- interests -->
              <text x="24" y="2144"><tspan class="prompt">$ </tspan><tspan class="cmd">echo $INTERESTS</tspan></text>
              <text x="24" y="2168"><tspan class="bullet">- </tspan><tspan class="text">Folding intricate origami</tspan></text>
              <text x="24" y="2192"><tspan class="bullet">- </tspan><tspan class="text">Participating in cultural activities</tspan></text>
              <text x="24" y="2216"><tspan class="bullet">- </tspan><tspan class="text">Volunteering for causes close to my heart</tspan></text>
              
              <!-- socials -->
              <text x="24" y="2264"><tspan class="prompt">$ </tspan><tspan class="cmd">socials</tspan></text>
              <text x="24" y="2288"><tspan class="text">üîó LinkedIn: </tspan><tspan class="link">https://linkedin.com/in/aryangupta0102</tspan></text>
              <text x="24" y="2312"><tspan class="text">üìß Email: </tspan><tspan class="warn">aryansumit0102@gmail.com</tspan></text>
              <text x="24" y="2336"><tspan class="text">üåê Portfolio: </tspan><tspan class="link">https://aryan-sgupta.com</tspan></text>
              <text x="24" y="2360"><tspan class="text">üêô GitHub: </tspan><tspan class="link">https://github.com/Aryan0102</tspan></text>
              <text x="24" y="2384"><tspan class="text">üì± Phone: </tspan><tspan class="warn">(570) 236-4213</tspan></text>

              <!-- exit -->
              <text x="24" y="2432"><tspan class="prompt">$ </tspan><tspan class="cmd">exit</tspan></text>
          '

          # -------------------------------
          # SVG Build
          # -------------------------------
          cat > console.svg <<SVG
          <?xml version="1.0" encoding="UTF-8"?>
          <svg width="$WIDTH" height="$HEIGHT" viewBox="0 0 $WIDTH $HEIGHT" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
            <title id="title">$TITLE</title>
            <desc id="desc">$DESCRIPTION</desc>
            <defs>
              <style>
                .t { font: $FONT; }
                .prompt { fill: $COLOR_PROMPT; font-weight: 700; }
                .cmd { fill: $COLOR_CMD; }
                .text { fill: $COLOR_TEXT; }
                .dim { fill: $COLOR_DIM; }
                .accent { fill: $COLOR_ACCENT; font-weight: 700; }
                .bullet { fill: $COLOR_PROMPT; }
                .link { fill: $COLOR_LINK; text-decoration: underline; }
                .warn { fill: $COLOR_WARN; }
                .success { fill: $COLOR_SUCCESS; font-weight: 600; }
                .barTitle { fill: $COLOR_TEXT; font: 13px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; }
              </style>
            </defs>

            <!-- window background -->
            <rect x="0" y="0" width="$WIDTH" height="$HEIGHT" rx="12" fill="$COLOR_BG" />
            <!-- title bar -->
            <rect x="0" y="0" width="$WIDTH" height="40" rx="12" fill="$COLOR_BAR" />
            <circle cx="22" cy="20" r="7" fill="$COLOR_CLOSE"/>
            <circle cx="44" cy="20" r="7" fill="$COLOR_MIN"/>
            <circle cx="66" cy="20" r="7" fill="$COLOR_MAX"/>
            <text x="90" y="25" class="barTitle">aryan@github: ~  ‚Äî  console</text>

            <!-- content -->
            <g class="t">
            $CONSOLE_CONTENT
            </g>
          </svg>
          SVG

      - name: Commit SVG if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update console.svg"
          file_pattern: console.svg
