name: Update Console SVG

on:
  schedule:
    - cron: "0 0 * * *" # once a day at midnight UTC
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build console.svg
        run: |
          # -------------------------------
          # CONFIG
          # -------------------------------
          WIDTH=980
          HEIGHT=1060
          FONT="14px/24px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"
          TITLE="Aryan Gupta — Console README"
          DESCRIPTION="Console style read me profile"

          COLOR_BG="#0d1117"
          COLOR_BAR="#161b22"
          COLOR_CLOSE="#ff5f57"
          COLOR_MIN="#febc2e"
          COLOR_MAX="#28c840"
          COLOR_PROMPT="#3fb950"
          COLOR_CMD="#79c0ff"
          COLOR_TEXT="#c9d1d9"
          COLOR_DIM="#8b949e"
          COLOR_ACCENT="#e3b341"
          COLOR_LINK="#58a6ff"
          COLOR_WARN="#f85149"

          # -------------------------------
          # CONSOLE CONTENT
          # -------------------------------
          CONSOLE_CONTENT='
              <!-- whoami -->
              <text x="24" y="80"><tspan class="prompt">$ </tspan><tspan class="cmd">whoami</tspan></text>
              <text x="24" y="104" class="text"><tspan class="accent">Aryan Gupta</tspan> — Student @ Northeastern University (Khoury College of Computer Sciences)</text>

              <!-- about-me -->
              <text x="24" y="152"><tspan class="prompt">$ </tspan><tspan class="cmd">about-me</tspan></text>
              <text x="24" y="176" class="dim">&gt; Passionate about blending technology with creativity to address real-world challenges.</text>
              <text x="24" y="200" class="dim">&gt; Experienced in web development, AI, and software engineering with focus on</text>
              <text x="24" y="224" class="dim">  front-end design, back-end development, and machine learning.</text>
              <text x="24" y="248" class="dim">&gt; Projects from interactive React + TypeScript platforms to AI research in Optical Neural Networks.</text>
              <text x="24" y="272" class="dim">&gt; Always eager to learn, create, and collaborate.</text>

              <!-- current project -->
              <text x="24" y="320"><tspan class="prompt">$ </tspan><tspan class="cmd">current-project</tspan></text>
              <text x="24" y="344" class="accent">Rainfall Learning</text>
              <text x="24" y="368" class="dim">&gt; An all-in-one platform for high school students to:</text>
              <text x="24" y="392"><tspan class="bullet">  •</tspan><tspan class="text"> Access live tutoring</tspan></text>
              <text x="24" y="416"><tspan class="bullet">  •</tspan><tspan class="text"> Collaborate in real-time coding</tspan></text>
              <text x="24" y="440"><tspan class="bullet">  •</tspan><tspan class="text"> Learn from a structured Python curriculum</tspan></text>
              <text x="24" y="464" class="dim">&gt; Open to developers, educators, and passionate collaborators.</text>

              <!-- interests -->
              <text x="24" y="512"><tspan class="prompt">$ </tspan><tspan class="cmd">interests</tspan></text>
              <text x="24" y="536"><tspan class="bullet">- </tspan><tspan class="text">Folding intricate origami</tspan></text>
              <text x="24" y="560"><tspan class="bullet">- </tspan><tspan class="text">Participating in cultural activities</tspan></text>
              <text x="24" y="584"><tspan class="bullet">- </tspan><tspan class="text">Volunteering for causes close to my heart</tspan></text>

              <!-- socials -->
              <text x="24" y="632"><tspan class="prompt">$ </tspan><tspan class="cmd">socials</tspan></text>
              <text x="24" y="656"><tspan class="text">🔗 LinkedIn: </tspan><tspan class="link">https://linkedin.com/in/aryangupta0102</tspan></text>
              <text x="24" y="680"><tspan class="text">📧 Email: </tspan><tspan class="warn">aryansumit0102@gmail.com</tspan></text>

              <!-- tech stack -->
              <text x="24" y="728"><tspan class="prompt">$ </tspan><tspan class="cmd">tech-stack --list</tspan></text>
              <text x="24" y="752" class="dim">CSS • Go • GraphQL • HTML • Java • JavaScript • LaTeX • Markdown • Python • TypeScript • Swift</text>
              <text x="24" y="776" class="dim">AWS • Netlify • Render • Vercel • Apollo • Django • Express.js • Expo • Flask • MUI • JWT</text>
              <text x="24" y="800" class="dim">NPM • Node.js • Nodemon • OpenCV • React • React Native • React Query • React Router • React Hook Form</text>
              <text x="24" y="824" class="dim">Socket.io • TailwindCSS • Yarn • Vite • Firebase • Postgres • MongoDB • Supabase • Prisma</text>
              <text x="24" y="848" class="dim">Figma • Matplotlib • NumPy • Pandas • PyTorch • TensorFlow • GitHub Actions • GitHub • Docker</text>
              <text x="24" y="872" class="dim">OpenAPI • Raspberry Pi • Prettier • Postman • Swagger • Twilio</text>

              <!-- exit -->
              <text x="24" y="920"><tspan class="prompt">$ </tspan><tspan class="cmd">exit</tspan></text>
          '

          # -------------------------------
          # SVG Build
          # -------------------------------
          cat > console.svg <<SVG
          <?xml version="1.0" encoding="UTF-8"?>
          <svg width="$WIDTH" height="$HEIGHT" viewBox="0 0 $WIDTH $HEIGHT" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
            <title id="title">$TITLE</title>
            <desc id="desc">$DESCRIPTION</desc>
            <defs>
              <style>
                .t { font: $FONT; }
                .prompt { fill: $COLOR_PROMPT; font-weight: 700; }
                .cmd { fill: $COLOR_CMD; }
                .text { fill: $COLOR_TEXT; }
                .dim { fill: $COLOR_DIM; }
                .accent { fill: $COLOR_ACCENT; font-weight: 700; }
                .bullet { fill: $COLOR_PROMPT; }
                .link { fill: $COLOR_LINK; text-decoration: underline; }
                .warn { fill: $COLOR_WARN; }
                .barTitle { fill: $COLOR_TEXT; font: 13px ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; }
              </style>
            </defs>

            <!-- window background -->
            <rect x="0" y="0" width="$WIDTH" height="$HEIGHT" rx="12" fill="$COLOR_BG" />
            <!-- title bar -->
            <rect x="0" y="0" width="$WIDTH" height="40" rx="12" fill="$COLOR_BAR" />
            <circle cx="22" cy="20" r="7" fill="$COLOR_CLOSE"/>
            <circle cx="44" cy="20" r="7" fill="$COLOR_MIN"/>
            <circle cx="66" cy="20" r="7" fill="$COLOR_MAX"/>
            <text x="90" y="25" class="barTitle">aryan@github: ~  —  console</text>

            <!-- content -->
            <g class="t">
            $CONSOLE_CONTENT
            </g>
          </svg>
          SVG

      - name: Commit SVG if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update console.svg"
          file_pattern: console.svg
